###USERS
POST http://localhost:8080/user
Content-Type: application/json

{
  "name": "test user",
  "email": "test@test.spbu.ru"
}

###
GET http://localhost:8080/user/13

###
PUT http://localhost:8080/user/1/toGroup/1

###
GET  http://localhost:8080/user/1/events

###GROUPS
POST http://localhost:8080/group
Content-Type: application/json

{
  "id": 1,
  "name": "some group"
}

###
GET http://localhost:8080/group

###EVENTS
POST http://localhost:8080/event
Content-Type: application/json

{
  "id": 1,
  "name": "english 2",
  "location": {
    "id": 1,
    "name": "English 2",
    "coordinates": "0"
  },
  "time": 1,
  "week_day": 0
}

###
GET http://localhost:8080/event

###
POST http://localhost:8080/event/5/adduser/1
Content-Type: application/json

###LOCATION
GET http://localhost:8080/location

###
POST http://localhost:8080/location
Content-Type: application/json

{
  "id": 1,
  "name": "PM-PU",
  "coordinates": "2"
}
