###
POST http://localhost:8080/user
Content-Type: application/json

{
  "name": "test user",
  "email": "test@test.spbu.ru"
}

###
GET http://localhost:8080/user/13

###
PUT http://localhost:8080/user/13/toGroup/2

###
POST http://localhost:8080/group
Content-Type: application/json

{
  "id": 1,
  "name": "some group"
}

###
GET http://localhost:8080/group

###
POST http://localhost:8080/event
Content-Type: application/json

{
  "id": 1,
  "name": "data bases",
  "location": {
    "id" : 0,
    "name": "2009",
    "coordinates" : "9988129, 981923"
  },
  "time": 930
}

###
GET http://localhost:8080/event

###
POST http://localhost:8080/event/1/adduser/1
Content-Type: application/json

###
GET http://localhost:8080/location

###
POST clocation
Content-Type: application/json

{
  "id": 1,
  "name": "university",
  "coordinates": "1"
}
